name: build main
on:
  push:
    branches-ignore:
      - "python/*"
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.8.10 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build python
        uses: ./.github/actions/python_build
      - name: upload artefacts
        uses: ./.github/actions/upload_artefacts